name: latest-deployment-openeye
channels:
  - conda-forge
  - openeye
dependencies:
  - openff-bespokefit
  - openff-toolkit =0.16
  - openeye-toolkits
  - xtb-python
  - pytest
  - pytest-cov
  - pytest-asyncio
  - pytest-celery
  - requests-mock
