name: latest-deployment
channels:
  - conda-forge
dependencies:
  - openff-bespokefit
  - openff-toolkit =0.16
  - ambertools
  - xtb-python
  - pytest
  - pytest-cov
  - pytest-asyncio
  - pytest-celery
  - requests-mock
